namespace MontraFleet.Api.Models;

public class Vehicle { public Guid Id { get; set; }=Guid.NewGuid(); public string Vin { get; set; }=string.Empty; public string RegistrationNumber { get; set; }=string.Empty; public string Model { get; set; }=string.Empty; public string Variant { get; set; }=string.Empty; public string Status { get; set; }="Available"; public decimal OdometerKm { get; set; } public decimal OperatingHours { get; set; } public decimal? BatterySoc { get; set; } }
public class PmObligation { public Guid Id { get; set; }=Guid.NewGuid(); public Guid VehicleId { get; set; } public string PlanCode { get; set; }=string.Empty; public string TriggerType { get; set; }=string.Empty; public DateTime? DueDate { get; set; } public decimal? DueReading { get; set; } public string Status { get; set; }="Upcoming"; }
public class Appointment { public Guid Id { get; set; }=Guid.NewGuid(); public Guid VehicleId { get; set; } public Guid? PmObligationId { get; set; } public DateTime StartAt { get; set; } public string ServiceCentre { get; set; }=string.Empty; public string Bay { get; set; }=string.Empty; public string Status { get; set; }="Scheduled"; }
public class ServiceEvent { public Guid Id { get; set; }=Guid.NewGuid(); public Guid VehicleId { get; set; } public string EventNumber { get; set; }=string.Empty; public string EventType { get; set; }=string.Empty; public string Status { get; set; }="Open"; public DateTime OpenedAt { get; set; }=DateTime.UtcNow; }
public class JobCard { public Guid Id { get; set; }=Guid.NewGuid(); public Guid ServiceEventId { get; set; } public string JobCardNumber { get; set; }=string.Empty; public string Status { get; set; }="Open"; public string Bay { get; set; }=string.Empty; public string Technician { get; set; }=string.Empty; }
public class WorkItem { public Guid Id { get; set; }=Guid.NewGuid(); public Guid JobCardId { get; set; } public string Description { get; set; }=string.Empty; public string Status { get; set; }="Pending"; public decimal? StandardRepairHours { get; set; } }
public class VehicleAvailabilityLedger { public Guid Id { get; set; }=Guid.NewGuid(); public Guid VehicleId { get; set; } public string State { get; set; }="Available"; public DateTime StartAt { get; set; }=DateTime.UtcNow; public DateTime? EndAt { get; set; } public string ReasonCode { get; set; }=string.Empty; public Guid? SourceServiceEventId { get; set; } }
