import {ControlComponent} from './features/control/control.component';
import { AiConfigurationComponent } from './features/ai-configuration/ai-configuration.component';
import { Routes } from '@angular/router';
import { DashboardComponent } from './features/dashboard/dashboard.component';
import { VehicleComponent } from './features/vehicle/vehicle.component';
import { PmComponent } from './features/pm/pm.component';
import { PmObligationsComponent } from './features/pm-obligations/pm-obligations.component';
import { ServiceComponent } from './features/service/service.component';
import { ServiceWorkspaceComponent } from './features/service-workspace/service-workspace.component';
import { TasksComponent } from './features/tasks/tasks.component';
import { BreakdownComponent } from './features/breakdown/breakdown.component';
import { JobCardComponent } from './features/job-card/job-card.component';
import { PartsComponent } from './features/parts/parts.component';
import { ReleaseComponent } from './features/release/release.component';
import { AvailabilityComponent } from './features/availability/availability.component';
import { AppointmentsComponent } from './features/appointments/appointments.component';
import { TechniciansComponent } from './features/technicians/technicians.component';
import { ChecklistComponent } from './features/checklist/checklist.component';
import { OffhireComponent } from './features/offhire/offhire.component';
import { QualityComponent } from './features/quality/quality.component';
import { AuditComponent } from './features/audit/audit.component';
import { SlaComponent } from './features/sla/sla.component';
import { WarrantyComponent } from './features/warranty/warranty.component';
import { CampaignsComponent } from './features/campaigns/campaigns.component';
import { DocumentsComponent } from './features/documents/documents.component';
import { SearchComponent } from './features/search/search.component';
import { MaintenanceRequestsComponent } from './features/maintenance-requests/maintenance-requests.component';
import { WorkOrdersComponent } from './features/work-orders/work-orders.component';
import { ServiceTaskMasterComponent } from './features/service-task-master/service-task-master.component';
import { MaintenanceAnalyticsComponent } from './features/maintenance-analytics/maintenance-analytics.component';
import { PmProgramMatrixComponent } from './features/pm-program-matrix/pm-program-matrix.component';
export const routes: Routes=[
{path:'',component:DashboardComponent},{path:'ai-configuration',component:AiConfigurationComponent},{path:'maintenance-requests',component:MaintenanceRequestsComponent},{path:'work-orders',component:WorkOrdersComponent},{path:'service-task-master',component:ServiceTaskMasterComponent},{path:'maintenance-analytics',component:ControlComponent,data:{section:'maintenance-analytics'}},{path:'pm-programs',component:PmProgramMatrixComponent},{path:'pm-obligations',component:PmObligationsComponent},{path:'search',component:SearchComponent},{path:'vehicle',component:VehicleComponent},{path:'pm',component:PmComponent},{path:'appointments',component:AppointmentsComponent},{path:'technicians',component:TechniciansComponent},{path:'service',component:ServiceComponent},{path:'service-workspace/:id',component:ServiceWorkspaceComponent},{path:'tasks',component:TasksComponent},{path:'breakdown',component:BreakdownComponent},{path:'job-card',component:JobCardComponent},{path:'checklist',component:ChecklistComponent},{path:'parts',component:PartsComponent},{path:'warranty',component:ControlComponent,data:{section:'warranty'}},{path:'campaigns',component:CampaignsComponent},{path:'documents',component:ControlComponent,data:{section:'documents'}},{path:'sla',component:ControlComponent,data:{section:'sla'}},{path:'release',component:ControlComponent,data:{section:'release'}},{path:'availability',component:ControlComponent,data:{section:'availability'}},{path:'offhire',component:ControlComponent,data:{section:'offhire'}},{path:'quality',component:ControlComponent,data:{section:'quality'}},{path:'audit',component:ControlComponent,data:{section:'audit'}},{path:'**',redirectTo:''}];
