import {VeeraiComponent} from './shared/veerai.component';
import {PageToolsComponent} from './shared/page-tools.component';
import {Component,ViewEncapsulation,HostListener} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {Router,NavigationEnd,RouterLink,RouterLinkActive,RouterOutlet} from '@angular/router';

@Component({selector:'app-root',standalone:true,imports:[VeeraiComponent,PageToolsComponent,CommonModule,FormsModule,RouterOutlet,RouterLink,RouterLinkActive],encapsulation:ViewEncapsulation.None,template:`
<div class="shell" [class.navigation-collapsed]="navigationCollapsed" [class.navigation-open]="navigationOpen"><button class="nav-backdrop" [hidden]="!navigationOpen" (click)="navigationOpen=false" aria-label="Close navigation"></button><aside id="fleet-navigation"><div class="brand"><img src="assets/audree-logo.png" alt="Audree" class="brand-logo"><strong>AUDREE</strong><button class="nav-close" (click)="navigationOpen=false" aria-label="Close navigation">×</button></div><nav aria-label="Main navigation" (click)="closeNavigation($event)">
 <section class="nav-section"><button class="nav-group" (click)="toggleGroup('Operations')" [attr.aria-expanded]="!collapsed['Operations']" aria-controls="nav-Operations"><span>Operations</span><span aria-hidden="true">{{collapsed['Operations']?'▸':'▾'}}</span></button><div class="nav-links" id="nav-Operations" [hidden]="collapsed['Operations']"><a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Dashboard</a><a routerLink="/appointments" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Appointments & Capacity</a><a routerLink="/service" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Service Execution</a><a routerLink="/breakdown" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Breakdowns / RSA</a></div></section>
 <section class="nav-section"><button class="nav-group" (click)="toggleGroup('Maintenance')" [attr.aria-expanded]="!collapsed['Maintenance']" aria-controls="nav-Maintenance"><span>Maintenance</span><span aria-hidden="true">{{collapsed['Maintenance']?'▸':'▾'}}</span></button><div class="nav-links" id="nav-Maintenance" [hidden]="collapsed['Maintenance']"><a routerLink="/maintenance-requests" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Maintenance Requests</a><a routerLink="/work-orders" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Work Orders</a><a routerLink="/tasks" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Task Management</a><a routerLink="/pm" [queryParams]="{tab:'history'}" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'exact',fragment:'ignored',matrixParams:'ignored'}">PM History</a></div></section>
 <section class="nav-section"><button class="nav-group" (click)="toggleGroup('Fleet')" [attr.aria-expanded]="!collapsed['Fleet']" aria-controls="nav-Fleet"><span>Fleet</span><span aria-hidden="true">{{collapsed['Fleet']?'▸':'▾'}}</span></button><div class="nav-links" id="nav-Fleet" [hidden]="collapsed['Fleet']"><a routerLink="/search" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Global Search</a><a routerLink="/vehicle" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Vehicle 360</a><a routerLink="/pm-obligations" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">PM Obligations</a><a routerLink="/campaigns" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Campaigns</a></div></section>
 <section class="nav-section"><button class="nav-group" (click)="toggleGroup('Configuration')" [attr.aria-expanded]="!collapsed['Configuration']" aria-controls="nav-Configuration"><span>Configuration</span><span aria-hidden="true">{{collapsed['Configuration']?'▸':'▾'}}</span></button><div class="nav-links" id="nav-Configuration" [hidden]="collapsed['Configuration']"><a routerLink="/pm" [queryParams]="{tab:'masters',focus:'fleet'}" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'exact',fragment:'ignored',matrixParams:'ignored'}">Fleet Masters</a><a routerLink="/pm-programs" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">PM Programs</a><a routerLink="/pm" [queryParams]="{tab:'enrollment'}" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'exact',fragment:'ignored',matrixParams:'ignored'}">Vehicle Enrollment</a><a routerLink="/pm" [queryParams]="{tab:'masters',focus:'system'}" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'exact',fragment:'ignored',matrixParams:'ignored'}">System Masters</a><a routerLink="/ai-configuration" routerLinkActive="active">AI Configuration</a></div></section>
 <section class="nav-section"><button class="nav-group" (click)="toggleGroup('Resources')" [attr.aria-expanded]="!collapsed['Resources']" aria-controls="nav-Resources"><span>Resources</span><span aria-hidden="true">{{collapsed['Resources']?'▸':'▾'}}</span></button><div class="nav-links" id="nav-Resources" [hidden]="collapsed['Resources']"><a routerLink="/technicians" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Technicians</a><a routerLink="/parts" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Parts & Inventory</a></div></section>
 <section class="nav-section"><button class="nav-group" (click)="toggleGroup('Control')" [attr.aria-expanded]="!collapsed['Control']" aria-controls="nav-Control"><span>Control</span><span aria-hidden="true">{{collapsed['Control']?'▸':'▾'}}</span></button><div class="nav-links" id="nav-Control" [hidden]="collapsed['Control']"><a routerLink="/warranty" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Warranty</a><a routerLink="/documents" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Documents</a><a routerLink="/sla" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">SLA Clocks</a><a routerLink="/release" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">QC / Release</a><a routerLink="/availability" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Availability / Uptime</a><a routerLink="/offhire" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Off-Hire</a><a routerLink="/quality" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Quality / FTF</a><a routerLink="/maintenance-analytics" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Maintenance Analytics</a><a routerLink="/audit" routerLinkActive="active" [routerLinkActiveOptions]="{paths:'exact',queryParams:'ignored',fragment:'ignored',matrixParams:'ignored'}">Audit Trail</a></div></section>
 </nav><div class="version">Montra Fleet Maintenance<br>v1.8.25 · Fleet Workspace</div></aside>
 <main><header class="app-header"><button class="menu-toggle" (click)="toggleNavigation()" aria-controls="fleet-navigation" [attr.aria-expanded]="navigationOpen||(!compactNavigation&&!navigationCollapsed)" aria-label="Toggle navigation">☰</button><div class="product"><h1>Montra Fleet Maintenance</h1><p>Maintain Today. Move Tomorrow.</p></div><form class="header-search" (ngSubmit)="openGlobalSearch()"><input name="globalVehicle" [(ngModel)]="globalQuery" placeholder="Search vehicle no. / VIN" aria-label="Global vehicle search"><button type="submit">Search</button></form><div class="user">RK &nbsp; Ravi Kumar<br><small>Service Centre Manager</small></div></header><app-page-tools/><div id="fleet-page-content"><router-outlet /></div></main>
</div><app-veerai [jobId]="veeraiJobId"></app-veerai>`,styles:[`
.shell{display:grid;grid-template-columns:255px 1fr;min-height:100vh}.shell > aside{background:#071b3a;color:#fff;padding:18px 14px;position:relative}.brand-logo{width:42px;height:42px;object-fit:contain;background:#fff;border-radius:7px;padding:2px}.brand{display:flex;gap:10px;align-items:center;font-size:22px;margin-bottom:18px}.mark{font-size:32px;font-weight:900;color:#ff6a35}nav{display:grid;gap:2px;padding-bottom:70px}nav a{padding:7px 11px;color:#dbe7fa;text-decoration:none;border-radius:7px;font-size:12.5px;cursor:pointer}nav a.active,nav a:hover{background:#123b73;color:#fff}.nav-group{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#7890b2;margin:10px 10px 3px}.version{position:absolute;bottom:12px;left:18px;font-size:11px;color:#b9c6da}main{min-width:0}header{min-height:72px;background:#fff;border-bottom:1px solid #e5e7eb;display:grid;grid-template-columns:minmax(220px,1fr) minmax(280px,520px) minmax(190px,1fr);gap:18px;align-items:center;padding:0 28px}header h1{margin:0;font-size:20px}header p{margin:4px 0 0;color:#64748b;font-size:13px}.user{text-align:right;font-size:13px}.header-search{display:grid;grid-template-columns:1fr auto}.header-search input,.header-search button{min-height:42px;padding:8px 11px;border:1px solid #cbd5e1}.header-search input{border-radius:8px 0 0 8px}.header-search button{border-radius:0 8px 8px 0;background:#1266d5;color:#fff;border-color:#1266d5;font-weight:700}app-pm > .page > .tabs,app-pm .setup-guide{display:none!important}@media(max-width:1100px){header{grid-template-columns:1fr 1.2fr}.user{display:none}}@media(max-width:900px){.shell{grid-template-columns:1fr}.shell > aside{display:none}header{padding:10px 14px;grid-template-columns:1fr}.product p{display:none}.header-search{width:100%}}

/* Shared application shell */
.shell{grid-template-columns:220px minmax(0,1fr)}
.shell > aside{position:sticky;top:0;height:100dvh;overflow-y:auto;padding:16px 12px;scrollbar-width:thin}
.shell .brand{font-size:21px;gap:9px;margin-bottom:16px}.shell .brand-logo{width:36px;height:36px}
.shell nav{padding-bottom:20px;gap:3px}.shell nav a{min-height:36px;display:flex;align-items:center;padding:8px 10px;line-height:1.3;font-size:12px}
.shell .version{position:static;padding:16px 10px 8px;border-top:1px solid #25405e;font-size:10px}
.shell .app-header{position:sticky;top:0;z-index:20;min-height:72px;grid-template-columns:38px minmax(175px,1fr) minmax(200px,430px) auto;padding:10px 22px;gap:16px}
.shell .app-header h1{font-size:17px}.shell .app-header p{font-size:11px}
.shell .header-search input{min-width:0;width:100%;font-size:13px}.shell .header-search button{font-size:12px}
.menu-toggle,.nav-close{min-width:38px;min-height:38px;border:1px solid #dce4ee;background:#fff;color:#17375d;border-radius:7px;font-size:20px;cursor:pointer}
.nav-close,.nav-backdrop{display:none}.shell.navigation-collapsed{grid-template-columns:minmax(0,1fr)}.shell.navigation-collapsed > aside{display:none}
@media(max-width:1100px){.shell{grid-template-columns:minmax(0,1fr)}.shell > aside{display:none}.shell.navigation-open > aside{display:block;position:fixed;left:0;top:0;width:250px;height:100dvh;z-index:50;box-shadow:8px 0 30px #071b3a33}.nav-close{display:block;margin-left:auto;background:transparent;border-color:#456080;color:white}.nav-backdrop:not([hidden]){display:block;position:fixed;inset:0;background:#071b3a66;border:0;z-index:40}.shell .app-header{grid-template-columns:38px minmax(160px,1fr) minmax(200px,1fr)}.shell .user{display:none}}
@media(max-width:600px){.shell .app-header{grid-template-columns:38px 1fr;padding:10px 14px;gap:8px 12px}.shell .header-search{grid-column:1/-1}.shell .app-header h1{font-size:16px}.shell .app-header p{display:none}}

.shell .nav-group{display:flex;justify-content:space-between;align-items:center;width:100%;margin:8px 0 3px;padding:10px;border:0;border-radius:6px;background:#142f50;color:#fff;font-size:12px;font-weight:700;cursor:pointer;text-align:left;letter-spacing:.04em}.nav-links{display:grid;gap:2px}.nav-links[hidden]{display:none}.shell nav a{min-height:32px;padding:7px 10px}.nav-group:focus-visible{outline:2px solid #7dbaff}.nav-section{min-width:0}
/* Enterprise fleet shell refresh */
.shell{grid-template-columns:250px minmax(0,1fr);background:#eef3f8}
.shell > aside{background:linear-gradient(180deg,#061a38 0%,#0a2a55 58%,#103d73 100%);padding:18px 14px;box-shadow:8px 0 26px rgba(7,27,58,.14)}
.shell .brand{padding:0 8px 18px;border-bottom:1px solid rgba(255,255,255,.16);margin-bottom:14px}
.shell .brand strong{letter-spacing:.14em;font-size:19px}
.shell nav{gap:9px}.shell .nav-section{padding:0 2px}
.shell .nav-group{margin:0 0 4px;padding:10px 12px;border:1px solid rgba(255,255,255,.08);border-radius:10px;background:rgba(255,255,255,.09);color:#f7fbff;transition:.2s}
.shell .nav-group:hover{background:rgba(92,169,255,.25);transform:translateX(2px)}
.shell .nav-links{gap:3px;padding:2px 0 4px}
.shell nav a{position:relative;min-height:35px;padding:8px 10px 8px 29px;border-radius:9px;color:#c9d9ed;transition:.2s}
.shell nav a:before{content:"";position:absolute;left:13px;top:50%;width:5px;height:5px;border-radius:50%;background:#79a4d5;transform:translateY(-50%)}
.shell nav a:hover{background:rgba(255,255,255,.11);color:#fff;transform:translateX(2px)}
.shell nav a.active{background:linear-gradient(90deg,#2d7fe5,#1854a5);color:#fff;font-weight:700;box-shadow:0 5px 14px rgba(0,0,0,.18)}
.shell nav a.active:before{width:7px;height:7px;background:#fff}
.shell .version{color:#bdd0e8;border-top-color:rgba(255,255,255,.16);line-height:1.5}
.shell main{background:transparent;min-width:0}
.shell .app-header{min-height:78px;background:rgba(255,255,255,.97);border-bottom:1px solid #d7e3ef;box-shadow:0 4px 18px rgba(31,65,100,.08);padding:12px 28px}
.shell .product h1{color:#102a43;letter-spacing:-.02em}.shell .product p{color:#60758b}
.shell .menu-toggle{border-color:#d3e1ee;border-radius:10px;box-shadow:0 3px 10px rgba(22,61,101,.08)}
.shell .header-search input{background:#f8fbff;border-color:#d2e0ed}
.shell .header-search input:focus{outline:2px solid rgba(23,105,209,.2);border-color:#6da5e5}
.shell .header-search button{background:linear-gradient(135deg,#1c74df,#1254ae);border-color:#1254ae}
.shell .user{color:#17375d;line-height:1.35}
.shell #fleet-page-content{min-height:calc(100vh - 78px);padding:22px 28px 42px}
.shell #fleet-page-content .page{width:100%;max-width:none}
.shell #fleet-page-content .title{margin-bottom:22px}.shell #fleet-page-content .title h2{font-size:26px;letter-spacing:-.025em;color:#102a43}.shell #fleet-page-content .title p{color:#60758b}
.shell #fleet-page-content .card{border:1px solid #d9e5f0;border-radius:14px;box-shadow:0 8px 22px rgba(31,65,100,.07);background:#fff}
.shell #fleet-page-content .kpis{gap:14px}.shell #fleet-page-content .kpi{position:relative;overflow:hidden;padding:18px;border-radius:14px}
.shell #fleet-page-content .kpi:after{content:"";position:absolute;right:-28px;top:-28px;width:92px;height:92px;border-radius:50%;background:rgba(23,105,209,.08)}
.shell #fleet-page-content .kpi strong{font-size:30px;color:#102a43}.shell #fleet-page-content .grid{gap:16px}
.shell #fleet-page-content .section-head{padding-bottom:12px;border-bottom:1px solid #edf2f7}.shell #fleet-page-content .action-queue{grid-column:1/-1}
.shell #fleet-page-content .action-grid{gap:12px}.shell #fleet-page-content .action-item{border:1px solid #f0c98e;border-radius:12px;background:linear-gradient(180deg,#fffaf2,#fff5e7);padding:14px}
.shell #fleet-page-content .action-title b{color:#bd4e0b;font-size:26px}.shell #fleet-page-content .action-records a{display:block;padding:5px 0;color:#1769d1;font-size:12px;border-bottom:1px dashed #f0d7b4}
.shell #fleet-page-content .summary-grid>div{border:1px solid #e1eaf3;border-radius:11px;background:#f8fbff;padding:14px}
app-veerai{position:relative;z-index:35}
@media(max-width:900px){.shell #fleet-page-content{padding:16px}.shell #fleet-page-content .title h2{font-size:22px}}

`]})
export class AppComponent{
 veeraiJobId='';globalQuery='';navigationOpen=false;navigationCollapsed=false;compactNavigation=window.innerWidth<=1100;
 @HostListener('window:resize') resize(){this.compactNavigation=window.innerWidth<=1100;if(!this.compactNavigation)this.navigationOpen=false;}
 @HostListener('window:keydown.escape') closeDrawer(){this.navigationOpen=false;}
 toggleNavigation(){if(this.compactNavigation)this.navigationOpen=!this.navigationOpen;else {this.navigationCollapsed=!this.navigationCollapsed;try{localStorage.setItem('fleet-menu-collapsed',String(this.navigationCollapsed))}catch{}}}
 closeNavigation(event:MouseEvent){if((event.target as HTMLElement).closest('a'))this.navigationOpen=false;}

 collapsed:Record<string,boolean>={};
 constructor(private router:Router){try{this.collapsed=JSON.parse(localStorage.getItem('fleet-menu-groups')||'{}');this.navigationCollapsed=localStorage.getItem('fleet-menu-collapsed')==='true'}catch{}this.router.events.subscribe(e=>{if(e instanceof NavigationEnd)this.revealGroup(e.urlAfterRedirects)});this.revealGroup(this.router.url)}
 toggleGroup(name:string){this.collapsed[name]=!this.collapsed[name];try{localStorage.setItem('fleet-menu-groups',JSON.stringify(this.collapsed))}catch{}}
 revealGroup(url:string){const path=url.split(/[?#]/)[0];this.veeraiJobId=path.match(/^\/service-workspace\/([a-f0-9-]+)$/i)?.[1]||'';const group=path==='/pm'?(url.includes('history')?'Maintenance':'Configuration'):['/','/appointments','/service','/breakdown','/service-workspace'].some(x=>x==='/'?path==='/':path===x||path.startsWith(x+'/'))?'Operations':['/maintenance-requests','/work-orders','/tasks'].includes(path)?'Maintenance':['/search','/vehicle','/pm-obligations','/campaigns'].includes(path)?'Fleet':path==='/pm-programs'?'Configuration':['/technicians','/parts'].includes(path)?'Resources':'Control';this.collapsed[group]=false;}

 openGlobalSearch(){const q=this.globalQuery.trim();this.router.navigate(['/search'],{queryParams:q?{q}:undefined})}
}
