services:
  - type: web
    name: montra-fleet-api
    runtime: docker
    rootDir: backend/src/MontraFleet.Api
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
  - type: web
    name: montra-fleet-web
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist/montra-fleet-web/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
