services:
  - type: web
    name: AU-Fleet-Ops
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: AUTO_CREATE_DB
        value: "true"
      - key: DATABASE_URL
        sync: false
