import {Component,OnInit} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {HttpClient,HttpParams} from '@angular/common/http';
import {ActivatedRoute,RouterLink} from '@angular/router';
import {FleetDateComponent} from '../../shared/fleet-date.component';
import {FleetChoiceComponent} from '../../shared/fleet-choice.component';
@Component({selector:'app-control',standalone:true,imports:[CommonModule,FormsModule,RouterLink,FleetDateComponent,FleetChoiceComponent],templateUrl:'./control.component.html',styleUrl:'./control.component.css'})
export class ControlComponent implements OnInit {
 documentScope='Customer';documentKind='';documentModel='';modelMasters:any[]=[];manufacturerTypes=['Brochure','Owner Manual','Service Manual','Design / Drawing','Parts Catalogue','Service Bulletin','Other'];
 section='';title='';rows:any[]=[];vehicles:any[]=[];jobs:any[]=[];entitlements:any[]=[];parts:any[]=[];events:any[]=[];data:any=null;loading=false;busy=false;error='';message='';form='';draft:any={};file:File|null=null;operator='';q='';status='';vehicleId='';model='';serviceType='';from='';to='';auditUser='';auditAction='';page=1;total=0;tab='entitlements';record='';
 titles:any={warranty:'Warranty & Claims',documents:'Documents & Evidence',sla:'SLA Clocks',release:'QC & Vehicle Release',availability:'Availability & Uptime',offhire:'Off-Hire & Recommissioning',quality:'Quality / First-Time Fix','maintenance-analytics':'Maintenance Analytics',audit:'Audit Trail'};
 constructor(private h:HttpClient,private route:ActivatedRoute){}
 ngOnInit(){this.section=this.route.snapshot.data['section'];this.title=this.titles[this.section];this.record=this.route.snapshot.queryParamMap.get('record')||'';if(this.route.snapshot.queryParamMap.get('claims'))this.tab='claims';try{this.operator=localStorage.getItem('fleet-control-operator')||''}catch{}const now=new Date();this.to=now.toISOString().slice(0,10);this.from=new Date(now.getTime()-30*86400000).toISOString().slice(0,10);this.h.get<any[]>('/api/vehicles').subscribe({next:x=>this.vehicles=x,error:()=>this.error='Vehicle list could not be loaded.'});this.h.get<any[]>('/api/job-cards').subscribe({next:x=>this.jobs=x,error:()=>this.error='Job Card list could not be loaded.'});if(this.section==='sla')this.h.get<any[]>('/api/service-events/active').subscribe(x=>this.events=x.filter(e=>!['Closed','Cancelled'].includes(e.status)));if(this.section==='documents')this.h.get<any[]>('/api/pm/vehicle-models').subscribe({next:x=>this.modelMasters=x.filter(m=>m.isActive),error:()=>this.error='Vehicle model masters could not be loaded. Please refresh.'});this.load();}
 get report(){return ['quality','maintenance-analytics','availability'].includes(this.section)}
 get models(){return [...new Set(this.vehicles.map(v=>v.model))].sort()}
 params(){let p=new HttpParams();if(this.from)p=p.set('from',new Date(this.from+'T00:00:00Z').toISOString());if(this.to)p=p.set('to',new Date(new Date(this.to+'T00:00:00Z').getTime()+86400000).toISOString());if(this.vehicleId)p=p.set('vehicleId',this.vehicleId);if(this.model)p=p.set('model',this.model);if(this.serviceType)p=p.set('serviceType',this.serviceType);return p;}
 load(){this.loading=true;this.error='';let url='/api/'+this.section;let params=new HttpParams();if(this.section==='availability')url='/api/availability/report';if(this.section==='release')url='/api/control/jobs';if(this.section==='maintenance-analytics')url='/api/analytics/maintenance';if(this.section==='warranty'&&this.tab==='claims')url='/api/warranty/claims';if(this.report)params=this.params();if(this.section==='audit'){url='/api/control/audit';params=this.params().set('page',this.page).set('q',this.q).set('user',this.auditUser).set('action',this.auditAction)}
 this.h.get<any>(url,{params}).subscribe({next:x=>{this.loading=false;if(this.report){this.data=x;this.rows=x.rows||x.details||[]}else if(this.section==='audit'){this.rows=x.rows;this.total=x.total}else this.rows=x;if(this.section==='warranty'&&this.tab==='entitlements')this.entitlements=x;},error:e=>{this.loading=false;this.rows=[];this.data=null;this.error=this.reason(e)}});}
 reason(e:any){return e?.error?.message||'Unable to complete this action. Please retry.'}
 filtered(){return this.rows.filter(x=>(this.section!=='documents'||((x.documentScope||'Customer')===this.documentScope&&(!this.documentKind||x.documentType===this.documentKind)&&(!this.documentModel||x.vehicleModelMasterId===this.documentModel)))&&(!this.record||x.id===this.record)&&(!this.status||x.status===this.status)&&(!this.vehicleId||x.vehicleId===this.vehicleId||this.report)&&(!this.q||JSON.stringify(x).toLowerCase().includes(this.q.toLowerCase())))}
 statuses(){return [...new Set(this.rows.map(x=>x.status).filter(Boolean))].sort()}
 clear(){this.documentKind='';this.documentModel='';this.q='';this.status='';this.vehicleId='';this.model='';this.serviceType='';this.record='';this.auditUser='';this.auditAction='';this.page=1;this.load()}
 selectTab(t:string){this.tab=t;this.status='';this.record='';this.load()}
 jobsForVehicle(){return this.jobs.filter(j=>!this.draft.vehicleId||this.vehicles.find(v=>v.id===this.draft.vehicleId)?.registrationNumber===j.vehicle)}
 open(kind:string,row:any=null){this.error='';this.message='';this.form=kind;this.file=null;this.draft={documentScope:this.documentScope,vehicleModelMasterId:'',vehicleType:'',manufacturer:'',title:'',revision:'',vehicleId:'',jobCardId:'',documentType:this.documentScope==='Manufacturer'?'Owner Manual':'Service Evidence',entitlementType:'Vehicle Warranty',referenceNo:'',startDate:'',endDate:'',odometerLimitKm:null,expiresAt:'',clockType:'Resolution',targetMinutes:240,result:'',remarks:'',description:'',amount:0,...(row?{id:row.id}:{} )};if(kind==='claim'){this.h.get<any[]>('/api/warranty').subscribe(x=>this.entitlements=x)}if(kind==='approve')this.draft.result='Approve';if(kind==='claimDecision'){this.draft.currentStatus=row.status;this.draft.result=row.status==='Draft'?'Submitted':row.status==='Submitted'?'Approved':'Paid';}}
 documentTab(scope:string){this.documentScope=scope;this.form='';this.file=null;this.clear()}
 documentModels(){return this.modelMasters.filter(m=>!this.draft.vehicleType||m.vehicleTypeCode===this.draft.vehicleType)}
 get documentVehicleTypes(){return [...new Set(this.modelMasters.map(m=>m.vehicleTypeCode).filter(Boolean))].sort()}
 chooseDocumentModel(){const m=this.modelMasters.find(m=>m.id===this.draft.vehicleModelMasterId);this.draft.manufacturer=m?.manufacturerCode||'';this.draft.vehicleType=m?.vehicleTypeCode||this.draft.vehicleType}
 claimEntitlement(){const w=this.entitlements.find(w=>w.id===this.draft.warrantyEntitlementId);this.draft.vehicleId=w?.vehicleId||'';this.draft.jobCardId='';this.parts=[];}
 loadParts(){this.draft.partRequestId='';this.parts=[];if(this.draft.jobCardId)this.h.get<any[]>('/api/part-requests',{params:{jobCardId:this.draft.jobCardId}}).subscribe(x=>this.parts=x)}
 pickFile(e:Event){this.file=(e.target as HTMLInputElement).files?.[0]||null}
 submit(){if(this.busy)return;if(!this.operator.trim()){this.error='Enter the operator / inspector name.';return}try{localStorage.setItem('fleet-control-operator',this.operator.trim())}catch{}let url='';let body:any;const d=this.draft,user=this.operator.trim();
 if(this.form==='entitlement'){if(!d.vehicleId||!d.referenceNo.trim()||!d.startDate||!d.endDate||d.endDate<d.startDate){this.error='Select vehicle and enter reference and valid coverage dates.';return}url='/api/warranty';body={...d,startDate:new Date(d.startDate+'T00:00:00Z').toISOString(),endDate:new Date(d.endDate+'T00:00:00Z').toISOString(),coverageNotes:d.description||'',status:'Active'}}
 else if(this.form==='document'){if(!this.file||this.file.size>10*1024*1024){this.error='Select a PDF, PNG or JPEG file up to 10 MB.';return}if(d.documentScope==='Manufacturer'?(!d.vehicleModelMasterId||!d.title.trim()):!d.vehicleId){this.error=d.documentScope==='Manufacturer'?'Select vehicle type, model and enter document title.':'Select a vehicle.';return}url='/api/documents/upload';const f=new FormData();f.append('file',this.file);for(const key of ['vehicleId','jobCardId','expiresAt','documentType','documentScope','vehicleModelMasterId','title','revision'])f.append(key,d[key]||'');f.append('user',user);body=f;}
 else if(this.form==='offhire'){if(!d.vehicleId||!d.reasonCode?.trim()){this.error='Select vehicle and enter reason.';return}url='/api/offhire';body={...d,user,expectedReturnAt:d.expectedReturnAt?new Date(d.expectedReturnAt+'T00:00:00Z').toISOString():null}}
 else if(this.form==='clock'){if(!d.serviceEventId||d.targetMinutes<=0){this.error='Select service and a positive target.';return}url='/api/sla/'+d.serviceEventId;body={clockType:d.clockType,targetMinutes:Number(d.targetMinutes),user};}
 else if(['pause','resume','stop'].includes(this.form)){url='/api/sla/'+d.id+'/'+this.form;body={user,reason:d.remarks||''}}
 else if(['approve','recommission'].includes(this.form)){url='/api/offhire/'+d.id+'/'+this.form;body={user,result:d.result,remarks:d.remarks}}
 else if(this.form==='claim'){if(!d.warrantyEntitlementId||!d.jobCardId||!d.description?.trim()){this.error='Select entitlement, linked Job Card and describe the claim.';return}url='/api/warranty/claims';body={warrantyEntitlementId:d.warrantyEntitlementId,jobCardId:d.jobCardId,partRequestId:d.partRequestId||null,description:d.description,amount:Number(d.amount),user};}
 else if(this.form==='claimDecision'){url='/api/warranty/claims/'+d.id+'/decision';body={user,result:d.result,remarks:d.remarks}}
 if(!url)return;this.busy=true;this.error='';this.h.post(url,body,{headers:{'X-Operator':user}}).subscribe({next:()=>{this.busy=false;this.form='';this.message='Saved successfully.';this.load()},error:e=>{this.busy=false;this.error=this.reason(e)}});}
 pct(v:any){return v===null||v===undefined?'Not available':v+'%'}
 auditLink(x:any){return x.jobCardId?['/service-workspace',x.jobCardId]:x.path?[x.path]:null}
 prev(){if(this.page>1){this.page--;this.load()}}next(){if(this.page*50<this.total){this.page++;this.load()}}
}
