import {FleetGridDirective} from '../../shared/fleet-grid.directive';
import { FleetDateComponent } from '../../shared/fleet-date.component';
import {Component,OnInit} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {HttpClient} from '@angular/common/http';
import {RouterLink} from '@angular/router';

@Component({selector:'app-pm-obligations',standalone:true,imports:[FleetGridDirective,FleetDateComponent,CommonModule,FormsModule,RouterLink],template:`
<section class="page">
  <div class="title"><div><h2>PM Obligations</h2><p>System-generated preventive maintenance demand from vehicle enrollment and the approved PM program.</p></div><button class="btn btn-outline" (click)="recalculate()">Recalculate PM</button></div>
  <div class="summary"><div><span>Upcoming</span><b>{{count('Upcoming')}}</b></div><div><span>Due Soon</span><b>{{count('Due Soon')}}</b></div><div><span>Due</span><b>{{count('Due')}}</b></div><div><span>Overdue</span><b class="bad">{{count('Overdue')}}</b></div><div><span>Scheduled / Planned</span><b>{{count('Planned')}}</b></div><div><span>In Service</span><b>{{count('In Service')}}</b></div></div>
  <div class="note"><b>Flow:</b> PM Obligation → Appointment → Check-In → Work Order / Job Card → PM Matrix Execution → QC → Release.</div>
  <div class="card"><div class="fleet-grid-scroll" role="region" aria-label="Records" tabindex="0"><table fleetGrid><tr><th>Vehicle</th><th>Model / Variant</th><th>PM Level</th><th>Trigger</th><th>Current</th><th>Due Date</th><th>Due Reading</th><th>Remaining</th><th>Status</th><th>Action</th></tr>
  <tr *ngFor="let x of rows"><td><b>{{x.vehicle}}</b></td><td>{{x.model}}<small>{{x.variant}}</small></td><td><b>{{x.plan}}</b><small>{{x.planName}}</small></td><td>{{x.trigger}}</td><td>{{x.current}}</td><td class="date-cell"><app-fleet-date [value]="x.dueDate" [dateOnly]="true"></app-fleet-date></td><td>{{x.dueReadingDisplay||'—'}}</td><td>{{x.remaining}}</td><td><span class="pill" [class.bad]="x.status==='Overdue'" [class.warn]="x.status==='Due'||x.status==='Due Soon'">{{x.service?.status||x.status}}</span><small *ngIf="x.appointmentNumber">{{x.appointmentNumber}} · {{x.appointmentStatus}}</small><small *ngIf="x.service"><b>{{x.service.eventNo}} · {{x.service.jobCard}}</b><br>Assigned supervisor: {{x.service.assignedSupervisor||'Unassigned'}} · {{x.service.bay||'Bay not assigned'}}</small></td><td><button class="btn btn-primary" *ngIf="!['Planned','In Service'].includes(x.status)" (click)="schedule(x)">Schedule Appointment</button><span *ngIf="x.status==='Planned'">Appointment planned</span><a class="btn btn-primary" *ngIf="x.status==='In Service'&&x.service?.jobCardId" [routerLink]="['/service-workspace',x.service.jobCardId]">Open Service Workspace</a><a class="btn btn-outline" *ngIf="x.status==='In Service'&&!x.service?.jobCardId" routerLink="/service">View Service Status</a></td></tr>
  <tr *ngIf="!rows.length"><td colspan="9" class="empty">No PM obligations. Enroll a vehicle with an applicable PM Program, then recalculate PM.</td></tr></table></div></div>
</section>
<div class="backdrop" *ngIf="show"></div><div class="modal" *ngIf="show"><div class="modal-head"><div><h3>Schedule PM Appointment</h3><p>{{selected?.vehicle}} · {{selected?.plan}} · {{selected?.planName}}</p></div><button class="x" (click)="close()">×</button></div><div class="grid"><label>PM Obligation<input [value]="selected?.plan+' · '+selected?.due" disabled></label><label>Priority<select [(ngModel)]="form.priority"><option>P1</option><option>P2</option><option>P3</option><option>P4</option></select></label><label>Date / Time<input type="datetime-local" [(ngModel)]="form.startAt" (change)="loadCapacity()"></label><label>Planned Hours<input type="number" min="0.5" step="0.5" [(ngModel)]="form.plannedHours"></label><label>Service Centre<input [(ngModel)]="form.serviceCentre" placeholder="Service centre"></label><label>Bay<select [(ngModel)]="form.bay"><option value="">Select bay</option><option *ngFor="let b of capacity?.bays" [value]="b.bayCode">{{b.bayCode}} · {{b.bayType}} · {{b.bookedHours}}h booked</option><option *ngIf="!capacity?.bays?.length">Bay-01</option><option *ngIf="!capacity?.bays?.length">Bay-02</option><option *ngIf="!capacity?.bays?.length">Bay-03</option></select></label><label class="wide">Reason / Note<textarea [(ngModel)]="form.reason"></textarea></label></div><div class="actions"><button class="btn btn-outline" (click)="close()">Cancel</button><button class="btn btn-primary" [disabled]="saving" (click)="save()">{{saving?'Scheduling...':'Schedule Appointment'}}</button></div><p class="error" *ngIf="message">{{message}}</p></div>
`,styles:[`.page{padding:26px}.title{display:flex;justify-content:space-between;align-items:center}.title h2{margin:0}.title p{color:#64748b}.summary{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:16px 0}.summary div{background:#fff;border:1px solid #e2e8f0;border-radius:9px;padding:12px}.summary span{display:block;color:#64748b;font-size:11px}.summary b{font-size:22px}.bad{color:#b91c1c}.note{background:#eef6ff;border:1px solid #bfdbfe;border-radius:8px;padding:10px 12px;margin-bottom:12px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:12px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #e5e7eb;text-align:left;font-size:12px;vertical-align:top}td small{display:block;color:#64748b;margin-top:3px}.pill{padding:4px 8px;border-radius:12px;background:#e2e8f0}.pill.warn{background:#fef3c7;color:#92400e}.pill.bad{background:#fee2e2;color:#991b1b}.empty{text-align:center;color:#64748b;padding:22px}.btn{border:1px solid #cbd5e1;border-radius:7px;padding:8px 12px;background:#fff;cursor:pointer}.btn-primary{background:#1266d5;color:#fff;border-color:#1266d5}.backdrop{position:fixed;inset:0;background:rgba(15,23,42,.42);z-index:1000}.modal{position:fixed;z-index:1001;left:50%;top:50%;transform:translate(-50%,-50%);width:min(820px,94vw);background:#fff;border-radius:12px;padding:20px;box-shadow:0 24px 70px rgba(0,0,0,.25)}.modal-head{display:flex;justify-content:space-between}.modal-head h3{margin:0}.modal-head p{margin:5px 0;color:#64748b}.x{border:0;background:transparent;font-size:28px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin:16px 0}.wide{grid-column:1/-1}label{font-size:12px}input,select,textarea{display:block;width:100%;box-sizing:border-box;padding:9px;margin-top:4px;border:1px solid #cbd5e1;border-radius:6px}textarea{min-height:60px}.actions{display:flex;justify-content:flex-end;gap:8px}.error{color:#b91c1c}@media(max-width:1000px){.summary{grid-template-columns:repeat(3,1fr)}}`]})
export class PmObligationsComponent implements OnInit{
 rows:any[]=[];vehicles:any[]=[];appointments:any[]=[];selected:any=null;show=false;saving=false;message='';capacity:any;form:any={startAt:'',serviceCentre:'',bay:'',plannedHours:4,priority:'P3',reason:''};
 constructor(private h:HttpClient){}
 ngOnInit(){this.h.get<any[]>('/api/vehicles').subscribe(x=>{this.vehicles=x;this.load()})}
 load(){this.h.get<any[]>('/api/appointments').subscribe(a=>{this.appointments=a;this.h.get<any[]>('/api/service-events/active').subscribe(services=>{this.h.get<any[]>('/api/pm/due-board').subscribe(x=>this.rows=x.map(o=>{const ap=a.find(z=>z.pmObligationId===o.id&&!['Cancelled','No-show','Completed'].includes(z.status));if(!ap)return o;const service=services.find(s=>s.vehicleId===o.vehicleId);return {...o,status:ap.status==='In Progress'?'In Service':'Planned',appointmentNumber:ap.appointmentNumber,appointmentStatus:ap.status,service};}))})})}
 count(s:string){return this.rows.filter(x=>x.status===s).length}
 recalculate(){this.h.post('/api/pm/recalculate',{}).subscribe(()=>this.load())}
 vehicle(){return this.vehicles.find(v=>v.id===this.selected?.vehicleId)}
 schedule(x:any){this.selected=x;const v=this.vehicles.find(z=>z.id===x.vehicleId);this.form={startAt:'',serviceCentre:v?.serviceCentreCode||'',bay:'',plannedHours:4,priority:x.status==='Overdue'?'P2':'P3',reason:`${x.plan} preventive maintenance`};this.capacity=null;this.message='';this.show=true}
 close(){if(!this.saving)this.show=false}
 loadCapacity(){if(!this.form.startAt)return;const d=this.form.startAt.substring(0,10);this.h.get(`/api/capacity?date=${d}`).subscribe(x=>{this.capacity=x;const bays=this.capacity?.bays||[];if(bays.length&&!this.form.bay)this.form.bay=bays[0].bayCode})}
 save(){if(!this.form.startAt){this.message='Appointment date/time is required.';return}if(!this.form.bay){this.message='Select a service bay.';return}this.saving=true;this.message='';const body={vehicleId:this.selected.vehicleId,pmObligationId:this.selected.id,sourceType:'PM Obligation',sourceReference:this.selected.id,startAt:new Date(this.form.startAt).toISOString(),serviceCentre:this.form.serviceCentre||this.vehicle()?.serviceCentreCode||'Service Centre',bay:this.form.bay,technicianId:null,appointmentType:'PM',priority:this.form.priority,reason:this.form.reason,plannedHours:Number(this.form.plannedHours)||4,createdBy:'Service Centre Manager'};this.h.post('/api/appointments',body).subscribe({next:()=>{this.saving=false;this.show=false;this.load()},error:e=>{this.saving=false;this.message=e.error?.message||'Unable to schedule appointment'}})}
}
