USE MontraFleetMaintenance;
GO
IF OBJECT_ID('PmObligations') IS NULL CREATE TABLE PmObligations(Id UNIQUEIDENTIFIER PRIMARY KEY,VehicleId UNIQUEIDENTIFIER NOT NULL,PlanCode NVARCHAR(50) NOT NULL,TriggerType NVARCHAR(30) NOT NULL,DueDate DATETIME2 NULL,DueReading DECIMAL(18,2) NULL,Status NVARCHAR(30) NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('Appointments') IS NULL CREATE TABLE Appointments(Id UNIQUEIDENTIFIER PRIMARY KEY,VehicleId UNIQUEIDENTIFIER NOT NULL,PmObligationId UNIQUEIDENTIFIER NULL,StartAt DATETIME2 NOT NULL,ServiceCentre NVARCHAR(120) NOT NULL,Bay NVARCHAR(50) NULL,Status NVARCHAR(30) NOT NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF OBJECT_ID('ServiceEvents') IS NULL CREATE TABLE ServiceEvents(Id UNIQUEIDENTIFIER PRIMARY KEY,VehicleId UNIQUEIDENTIFIER NOT NULL,EventNumber NVARCHAR(50) NOT NULL UNIQUE,EventType NVARCHAR(50) NOT NULL,Status NVARCHAR(30) NOT NULL,OpenedAt DATETIME2 NOT NULL,ClosedAt DATETIME2 NULL);
GO
IF OBJECT_ID('JobCards') IS NULL CREATE TABLE JobCards(Id UNIQUEIDENTIFIER PRIMARY KEY,ServiceEventId UNIQUEIDENTIFIER NOT NULL,JobCardNumber NVARCHAR(50) NOT NULL UNIQUE,Status NVARCHAR(30) NOT NULL,Bay NVARCHAR(50) NULL,Technician NVARCHAR(120) NULL,OpenedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),ClosedAt DATETIME2 NULL);
GO
IF OBJECT_ID('WorkItems') IS NULL CREATE TABLE WorkItems(Id UNIQUEIDENTIFIER PRIMARY KEY,JobCardId UNIQUEIDENTIFIER NOT NULL,Description NVARCHAR(500) NOT NULL,Status NVARCHAR(30) NOT NULL,StandardRepairHours DECIMAL(8,2) NULL,ActualHours DECIMAL(8,2) NULL);
GO
IF OBJECT_ID('VehicleAvailabilityLedger') IS NULL CREATE TABLE VehicleAvailabilityLedger(Id UNIQUEIDENTIFIER PRIMARY KEY,VehicleId UNIQUEIDENTIFIER NOT NULL,State NVARCHAR(40) NOT NULL,StartAt DATETIME2 NOT NULL,EndAt DATETIME2 NULL,ReasonCode NVARCHAR(80) NULL,SourceServiceEventId UNIQUEIDENTIFIER NULL,CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
