USE MontraFleetMaintenance;
GO

CREATE TABLE ServiceBays (
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, ServiceCentre NVARCHAR(150) NOT NULL,
 BayCode NVARCHAR(40) NOT NULL, BayType NVARCHAR(50) NOT NULL, IsActive BIT NOT NULL DEFAULT 1,
 CONSTRAINT UQ_ServiceBays UNIQUE(ServiceCentre, BayCode)
);

CREATE TABLE Technicians (
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, EmployeeCode NVARCHAR(40) NOT NULL UNIQUE,
 Name NVARCHAR(150) NOT NULL, ServiceCentre NVARCHAR(150) NOT NULL, SkillCodes NVARCHAR(500) NULL,
 HvAuthorized BIT NOT NULL DEFAULT 0, HvAuthorizationValidUntil DATETIME2 NULL, IsActive BIT NOT NULL DEFAULT 1
);

CREATE TABLE ChecklistExecutions (
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, JobCardId UNIQUEIDENTIFIER NOT NULL, WorkItemId UNIQUEIDENTIFIER NULL,
 ChecklistCode NVARCHAR(80) NOT NULL, ItemCode NVARCHAR(80) NOT NULL, ItemText NVARCHAR(500) NOT NULL,
 Result NVARCHAR(30) NOT NULL, Remarks NVARCHAR(1000) NULL, ExecutedBy NVARCHAR(150) NULL,
 ExecutedAt DATETIME2 NULL, IsMandatory BIT NOT NULL DEFAULT 1
);

CREATE TABLE Defects (
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, VehicleId UNIQUEIDENTIFIER NOT NULL, JobCardId UNIQUEIDENTIFIER NOT NULL,
 WorkItemId UNIQUEIDENTIFIER NULL, DefectNumber NVARCHAR(60) NOT NULL UNIQUE, Category NVARCHAR(100) NULL,
 Severity NVARCHAR(30) NOT NULL, Description NVARCHAR(1000) NOT NULL, Disposition NVARCHAR(100) NOT NULL,
 FailureCode NVARCHAR(100) NULL, RcaSummary NVARCHAR(2000) NULL, ReportedAt DATETIME2 NOT NULL, ClosedAt DATETIME2 NULL
);

CREATE TABLE OffHireRecords (
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, VehicleId UNIQUEIDENTIFIER NOT NULL, StartAt DATETIME2 NOT NULL,
 ExpectedReturnAt DATETIME2 NULL, EndAt DATETIME2 NULL, ReasonCode NVARCHAR(100) NOT NULL,
 EvidenceReference NVARCHAR(500) NULL, RequestedBy NVARCHAR(150) NOT NULL, ApprovedBy NVARCHAR(150) NULL,
 Status NVARCHAR(50) NOT NULL
);

CREATE TABLE RecommissioningInspections (
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, OffHireRecordId UNIQUEIDENTIFIER NOT NULL, VehicleId UNIQUEIDENTIFIER NOT NULL,
 Inspector NVARCHAR(150) NULL, Result NVARCHAR(50) NOT NULL, Remarks NVARCHAR(1000) NULL, InspectedAt DATETIME2 NULL
);

CREATE TABLE RepeatFailureMatches (
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, VehicleId UNIQUEIDENTIFIER NOT NULL,
 SourceServiceEventId UNIQUEIDENTIFIER NOT NULL, RepeatServiceEventId UNIQUEIDENTIFIER NOT NULL,
 MatchKey NVARCHAR(150) NOT NULL, WindowDays INT NOT NULL DEFAULT 30, IsRepeat BIT NOT NULL, EvaluatedAt DATETIME2 NOT NULL
);
CREATE INDEX IX_RepeatFailureMatches ON RepeatFailureMatches(VehicleId, MatchKey, EvaluatedAt);

CREATE TABLE FirstTimeFixResults (
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, ServiceEventId UNIQUEIDENTIFIER NOT NULL, VehicleId UNIQUEIDENTIFIER NOT NULL,
 Eligible BIT NOT NULL, Passed BIT NOT NULL, Reason NVARCHAR(1000) NULL, EvaluatedAt DATETIME2 NOT NULL
);

CREATE TABLE ApprovalRecords (
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, EntityType NVARCHAR(100) NOT NULL, EntityId UNIQUEIDENTIFIER NOT NULL,
 Action NVARCHAR(100) NOT NULL, RequestedBy NVARCHAR(150) NOT NULL, ApprovedBy NVARCHAR(150) NULL,
 Status NVARCHAR(50) NOT NULL, RequestedAt DATETIME2 NOT NULL, ApprovedAt DATETIME2 NULL,
 CONSTRAINT CK_ApprovalRecords_MakerChecker CHECK (ApprovedBy IS NULL OR RequestedBy <> ApprovedBy)
);

CREATE TABLE AuditEvents (
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, OccurredAt DATETIME2 NOT NULL, UserName NVARCHAR(150) NOT NULL,
 Action NVARCHAR(100) NOT NULL, EntityType NVARCHAR(100) NOT NULL, EntityId UNIQUEIDENTIFIER NULL,
 CorrelationId NVARCHAR(100) NULL, Details NVARCHAR(MAX) NULL
);

ALTER TABLE Appointments ADD EndAt DATETIME2 NULL, AppointmentType NVARCHAR(50) NOT NULL DEFAULT 'PM', PlannedHours DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE JobCards ADD TechnicianId UNIQUEIDENTIFIER NULL;
ALTER TABLE WorkItems ADD RequiresHvAuthorization BIT NOT NULL DEFAULT 0;
ALTER TABLE PartTransactions ADD AuthorizationStatus NVARCHAR(50) NOT NULL DEFAULT 'Not Required';
ALTER TABLE QcInspections ADD RoadTestRequired BIT NOT NULL DEFAULT 0, RoadTestPassed BIT NOT NULL DEFAULT 0;
ALTER TABLE VehicleAvailabilityLedger ADD RuleVersion NVARCHAR(30) NOT NULL DEFAULT 'AVL-1.0', CorrectsLedgerId UNIQUEIDENTIFIER NULL;
GO
