import {Component,OnInit} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {RouterLink} from '@angular/router';
import {HttpClient} from '@angular/common/http';
import {FleetDateComponent} from '../../shared/fleet-date.component';
@Component({selector:'app-service',standalone:true,imports:[CommonModule,FormsModule,RouterLink,FleetDateComponent],template:`
<section class="page service-page">
 <div class="service-heading"><div><h2>Service Execution</h2><p>Track the vehicle, assigned supervisor and next action.</p></div><span>{{filtered().length}} of {{rows.length}} services</span></div>
 <div class="service-filters"><label>Find a service<input [(ngModel)]="search" placeholder="Vehicle, issue, event or job card"></label><label>Service type<select [(ngModel)]="type"><option value="">All types</option><option>Breakdown</option><option>PM</option><option>Maintenance</option></select></label><label>Status<select [(ngModel)]="status"><option value="">All statuses</option><option>Awaiting Assignment</option><option>Assigned</option><option>In Progress</option><option>On Hold</option><option>Open</option><option>Cancelled</option></select></label><button (click)="search='';type='';status=''">Clear</button></div>
 <p *ngIf="loading" role="status">Loading services…</p><p *ngIf="error" role="alert">{{error}} <button (click)="load()">Retry</button></p>
 <div class="service-list"><article class="service-record" *ngFor="let x of filtered();trackBy:trackService">
  <div class="service-summary">
   <div class="vehicle-block"><span class="field-label">Vehicle</span><strong>{{x.vehicle}}</strong><span class="service-type">{{x.type}}</span></div>
   <div class="complaint-block"><span class="field-label">Reported issue</span><b>{{x.complaint||(x.type==='PM'?'Scheduled preventive maintenance':'No issue recorded')}}</b><small *ngIf="x.breakdownLocation">{{x.breakdownLocation}} · {{x.dispatchMode}}</small></div>
   <div><span class="field-label">Assigned supervisor</span><b>{{x.assignedSupervisor||'Unassigned'}}</b><small>Bay: {{x.bay||'Not allocated'}}</small></div>
   <div class="service-next"><span class="service-state" [class.waiting]="x.status==='Awaiting Assignment'">{{x.status}}</span><span class="field-label">Action</span><a *ngIf="x.jobCardId" class="open-service" [routerLink]="['/service-workspace',x.jobCardId]">Open Workspace →</a></div>
  </div>
  <div class="service-dates"><div><span class="field-label">Reported On</span><app-fleet-date [value]="x.reportedAt"></app-fleet-date></div><div><span class="field-label">Service Opened On</span><app-fleet-date [value]="x.openedAt"></app-fleet-date></div><div><span class="field-label">Supervisor Assigned On</span><app-fleet-date [value]="x.supervisorAssignedAt"></app-fleet-date></div></div>
  <details class="service-references"><summary>Service references <span>{{x.eventNo}}</span></summary><div class="reference-grid"><div><span class="field-label">Service Event</span><b>{{x.eventNo}}</b></div><div><span class="field-label">Job Card</span><b>{{x.jobCard||'Not created'}}</b></div><div><span class="field-label">Breakdown Source</span><a *ngIf="x.breakdownNumber" [routerLink]="['/breakdown']" [queryParams]="{open:x.breakdownId}">{{x.breakdownNumber}}</a><span *ngIf="!x.breakdownNumber">—</span></div></div></details>
 </article></div>
 <div class="service-empty" *ngIf="!loading&&!error&&!filtered().length">No services match these filters.</div>
</section>`,styles:[`
.service-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:20px}.service-heading h2{margin:0 0 6px}.service-heading p{margin:0;color:#64748b}.service-heading>span{white-space:nowrap;font-size:12px;color:#64748b}.service-filters{display:grid;grid-template-columns:minmax(200px,2fr) 1fr 1fr auto;align-items:end;gap:12px;margin-bottom:18px}.service-filters label{display:grid;gap:6px;font-size:12px;color:#52647c}.service-filters input,.service-filters select,.service-filters button{height:44px;border:1px solid #cbd5e1;border-radius:8px;padding:9px 12px;background:#fff;min-width:0}.service-filters button{cursor:pointer;color:#1756a5}.service-list{display:grid;gap:14px}.service-record{border:1px solid #dce4ee;background:#fff;border-radius:12px;overflow:hidden}.service-summary{display:grid;grid-template-columns:minmax(135px,1fr) minmax(180px,1.7fr) minmax(135px,1fr) minmax(155px,auto);align-items:start;gap:20px;padding:18px}.field-label{display:block;color:#64748b;font-size:11px;font-weight:500;margin-bottom:6px}.vehicle-block strong{display:block;font-size:16px;white-space:nowrap}.service-type{display:inline-block;margin-top:8px;font-size:11px;background:#f0f4f8;padding:4px 8px;border-radius:5px}.service-summary b{font-size:13px;line-height:1.5}.service-summary small{display:block;color:#64748b;margin-top:6px;font-size:12px}.service-next{display:flex;flex-direction:column;align-items:flex-end;gap:12px}.service-state{background:#edf5ff;border-radius:20px;padding:5px 10px;font-size:12px;white-space:nowrap;color:#24568d}.service-state.waiting{color:#a34d0b;background:#fff4e7}.open-service{display:flex;align-items:center;min-height:42px;padding:9px 12px;border-radius:7px;background:transparent;color:#145cb7;text-decoration:underline;text-underline-offset:3px;white-space:nowrap;font-size:12px;font-weight:600}.service-dates{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding:12px 18px;background:#fafbfd;border-top:1px solid #edf1f6}.service-references{border-top:1px solid #edf1f6;font-size:12px}.service-references summary{padding:12px 18px;cursor:pointer;color:#37526f;min-height:42px}.service-references summary span{margin-left:12px;font-size:11px;color:#64748b;white-space:nowrap}.reference-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding:2px 18px 16px}.reference-grid b,.reference-grid a{white-space:nowrap;font-size:12px}.reference-grid a{color:#1463ce}.service-empty{padding:36px;text-align:center;border:1px dashed #cbd5e1;border-radius:12px;color:#64748b}
@media(max-width:1100px){.service-summary{grid-template-columns:1fr 1fr}.service-next{align-items:flex-start;flex-direction:row;flex-wrap:wrap;align-items:center}.service-filters{grid-template-columns:2fr 1fr 1fr}.service-filters button{grid-column:3}.service-dates{gap:10px}}
@media(max-width:600px){.service-heading{align-items:flex-start;flex-direction:column;gap:8px}.service-filters{grid-template-columns:1fr 1fr}.service-filters label:first-child{grid-column:1/-1}.service-filters button{grid-column:1/-1}.service-summary{padding:14px;gap:16px}.complaint-block{grid-column:1/-1;grid-row:2}.service-next{grid-column:1/-1;justify-content:space-between}.service-dates,.reference-grid{grid-template-columns:1fr;gap:12px;padding:14px}.service-dates>div{display:grid;grid-template-columns:1.1fr 1fr;align-items:start}.service-references summary span{display:block;margin:6px 0 0}.open-service{min-height:44px}}
`]})
export class ServiceComponent implements OnInit {
 rows:any[]=[];search='';type='';status='';loading=true;error='';
 constructor(private h:HttpClient){}
 ngOnInit(){this.load()}
 load(){this.loading=true;this.error='';this.h.get<any[]>('/api/service-events/active').subscribe({next:x=>{this.rows=x;this.loading=false},error:()=>{this.loading=false;this.error='Unable to load services.'}})}
 trackService(_:number,x:any){return x.id||x.eventNo}
 filtered(){const q=this.search.trim().toLowerCase();return this.rows.filter(x=>(!q||[x.eventNo,x.breakdownNumber,x.complaint,x.breakdownLocation,x.jobCard,x.vehicle,x.assignedSupervisor].some(v=>String(v||'').toLowerCase().includes(q)))&&(!this.type||x.type===this.type)&&(!this.status||x.status===this.status))}
}
