import {FleetGridDirective} from '../../shared/fleet-grid.directive';
import { FleetDateComponent } from '../../shared/fleet-date.component';
import {Component,OnInit} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute,RouterLink} from '@angular/router';
import {HttpClient} from '@angular/common/http';

@Component({selector:'app-vehicle',standalone:true,imports:[FleetGridDirective,FleetDateComponent,CommonModule,FormsModule,RouterLink],template:`
<section class="page">
 <div class="title"><h2>Vehicle Current Status</h2><p>One operational view of the vehicle, its active service and linked maintenance records.</p></div>
 <div class="vehicle-search"><input [(ngModel)]="query" (keyup.enter)="findVehicle()" placeholder="Enter vehicle registration number or VIN"><button (click)="findVehicle()">Search Vehicle</button><select [(ngModel)]="id" (change)="load()"><option value="">Select vehicle</option><option *ngFor="let x of vehicles" [value]="x.id">{{x.registrationNumber}} · {{x.model}}</option></select></div>
 <p class="error" *ngIf="message">{{message}}</p>
 <ng-container *ngIf="v">
  <div class="vehicle-head"><img *ngIf="v.imageUrl" [src]="v.imageUrl" [alt]="v.model" style="width:140px;height:90px;object-fit:contain"><div><span>Vehicle</span><h3>{{v.registration}} · {{v.model}}</h3><small>{{v.variant}} · VIN {{v.vin}}</small></div><span class="state">{{v.currentService?.stage||v.availability}}</span></div>
  <div class="stats"><div>Odometer<b>{{v.odometerKm|number:'1.0-0'}} km</b></div><div>Operating hours<b>{{v.operatingHours|number:'1.0-0'}} hr</b></div><div>Battery SOC<b>{{v.batterySoc==null?'-':v.batterySoc+'%'}}</b></div><div>Next PM<b>{{v.nextPm}}</b></div><div>Open defects<b>{{v.openDefects}}</b></div></div>
  <section class="current active" *ngIf="v.currentService as s; else noActiveService"><div class="section-head"><div><span>Current service status</span><h3>{{s.stage}}</h3></div><a class="btn primary" [routerLink]="['/service-workspace',s.jobCardId]">Open Service Workspace</a></div><div class="grid"><div><span>Service Event</span><b>{{s.eventNumber}}</b></div><div><span>Job Card</span><b>{{s.jobCardNumber}}</b></div><div><span>Type / Priority</span><b>{{s.eventType}} · {{s.priority}}</b></div><div><span>Opened</span><b><app-fleet-date [value]="s.openedAt"></app-fleet-date></b></div><div><span>Assigned To (Supervisor)</span><b>{{s.assignedSupervisor||'Unassigned'}}</b></div><div><span>Supervisor Assigned On</span><app-fleet-date [value]="s.supervisorAssignedAt"></app-fleet-date></div><div><span>Internal Technician</span><b>{{s.technician||'Awaiting assignment'}}</b></div><div><span>Bay</span><b>{{s.bay||'Not assigned'}}</b></div><div><span>Tasks</span><b>{{s.tasksCompleted}} / {{s.tasksTotal}}</b></div><div><span>Checks</span><b>{{s.checksCompleted}} / {{s.checksTotal}}</b></div><div><span>Parts waiting</span><b>{{s.partsWaiting}}</b></div><div><span>QC</span><b>{{s.qcStatus}}</b></div></div><div class="complaint" *ngIf="s.complaint"><span>Reported issue {{s.breakdownNumber}}</span><b>{{s.complaint}}</b></div></section>
  <ng-template #noActiveService><section class="current"><h3>No active service</h3><p>This vehicle currently has no open Service Event or Job Card.</p></section></ng-template>
  <section class="current" *ngIf="v.appointment as a"><div class="section-head"><div><span>Current appointment</span><h3>{{a.appointmentNumber}} · {{a.status}}</h3></div></div><div class="grid"><div><span>Scheduled</span><b><app-fleet-date [value]="a.startAt"></app-fleet-date></b></div><div><span>Type</span><b>{{a.appointmentType}}</b></div><div><span>Service centre</span><b>{{a.serviceCentre}}</b></div><div><span>Bay / Technician</span><b>{{a.bay||'-'}} · {{a.technician||'Unassigned'}}</b></div></div></section>
  <div class="two"><section class="card"><h3>Open Maintenance Requests</h3><div class="fleet-grid-scroll" role="region" aria-label="Records" tabindex="0"><table fleetGrid><tr><th>Request</th><th>Requested On</th><th>Description</th><th>Status</th></tr><tr *ngFor="let r of v.openRequests"><td><b>{{r.requestNumber}}</b></td><td class="date-cell"><app-fleet-date [value]="r.requestedAt"></app-fleet-date></td><td>{{r.description}}</td><td>{{r.status}}</td></tr><tr *ngIf="!v.openRequests?.length"><td colspan="4" class="empty">No open maintenance requests.</td></tr></table></div></section><section class="card"><h3>Service History</h3><div class="fleet-grid-scroll" role="region" aria-label="Records" tabindex="0"><table fleetGrid><tr><th>Event</th><th>Opened On</th><th>Closed On</th><th>Type</th><th>Status</th><th>Action</th></tr><tr *ngFor="let h of v.history"><td><b>{{h.eventNumber}}</b></td><td class="date-cell"><app-fleet-date [value]="h.openedAt"></app-fleet-date></td><td class="date-cell"><app-fleet-date [value]="h.closedAt"></app-fleet-date></td><td>{{h.eventType}}</td><td>{{h.status}}</td><td><a *ngIf="h.jobCardId" [routerLink]="['/service-workspace',h.jobCardId]">View</a></td></tr></table></div></section></div>
  <section class="card facts"><div><span>Warranty</span><b>{{v.activeWarranty?'Active':'No active coverage'}}</b></div><div><span>Campaigns</span><b>{{v.openCampaigns}}</b></div><div><span>Documents</span><b>{{v.documents}}</b></div><div><span>Last service</span><b><app-fleet-date [value]="v.lastService"></app-fleet-date></b></div></section>
 </ng-container>
</section>`,styles:[`
.page{padding:26px}.title h2{margin:0}.title p{color:#64748b}.vehicle-search{display:grid;grid-template-columns:minmax(260px,2fr) auto minmax(240px,1fr);gap:8px;margin:16px 0}.vehicle-search input,.vehicle-search select,.vehicle-search button{min-height:46px;padding:9px;border:1px solid #cbd5e1;border-radius:8px;background:#fff}.vehicle-search button,.btn.primary{background:#1266d5;color:#fff;border-color:#1266d5;font-weight:700}.vehicle-head,.section-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.vehicle-head{background:#fff;border:1px solid #dbe4ef;border-radius:12px;padding:14px}.vehicle-head span,.current span,.facts span{display:block;color:#64748b;font-size:11px}.vehicle-head h3,.section-head h3{margin:4px 0}.state{background:#eaf3ff!important;color:#0f4fa8!important;padding:8px 12px;border-radius:18px;font-size:13px!important}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:12px 0}.stats>div,.card,.current{background:#fff;border:1px solid #dbe4ef;border-radius:10px;padding:12px}.stats b{display:block;font-size:18px;margin-top:5px}.current{margin:12px 0}.current.active{border-left:5px solid #1266d5}.grid{display:grid;grid-template-columns:repeat(5,1fr);gap:9px;margin-top:12px}.grid>div,.complaint{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:9px}.grid b,.complaint b{display:block;margin-top:4px}.complaint{margin-top:10px;border-left:4px solid #f97316}.btn{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:8px 13px;border-radius:8px;text-decoration:none}.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.card h3{margin-top:0}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #e5e7eb;text-align:left;font-size:12px;vertical-align:top}td small{display:block;color:#64748b;margin-top:3px}td a{color:#1266d5;font-weight:700}.facts{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:12px}.facts b{display:block;margin-top:4px}.empty,.error{color:#64748b}.error{color:#b91c1c}@media(max-width:1000px){.stats,.grid{grid-template-columns:repeat(2,1fr)}.two{grid-template-columns:1fr}}@media(max-width:700px){.page{padding:10px}.vehicle-search{grid-template-columns:1fr}.vehicle-head,.section-head{align-items:stretch;flex-direction:column}.stats,.grid,.facts{grid-template-columns:1fr}.btn{width:100%;box-sizing:border-box}.card{overflow-x:auto}}
`]})
export class VehicleComponent implements OnInit{
 vehicles:any[]=[];id='';query='';v:any;message='';
 constructor(private h:HttpClient,private route:ActivatedRoute){}
 ngOnInit(){this.h.get<any[]>('/api/vehicles').subscribe(x=>{this.vehicles=x;const requested=this.route.snapshot.queryParamMap.get('id');this.id=requested&&x.some(v=>v.id===requested)?requested:(x[0]?.id||'');if(this.id)this.load()})}
 findVehicle(){const q=this.query.trim().toLowerCase();if(!q)return;const match=this.vehicles.find(x=>String(x.registrationNumber||'').toLowerCase()===q||String(x.vin||'').toLowerCase()===q)||this.vehicles.find(x=>String(x.registrationNumber||'').toLowerCase().includes(q)||String(x.vin||'').toLowerCase().includes(q));if(!match){this.message='No vehicle found for this registration number or VIN.';return}this.message='';this.id=match.id;this.load()}
 load(){if(this.id)this.h.get(`/api/vehicle360/${this.id}`).subscribe({next:x=>{this.v=x;this.message=''},error:()=>this.message='Unable to load the vehicle status.'})}
}
