import {FleetGridDirective} from '../../shared/fleet-grid.directive';
import { FleetDateComponent } from '../../shared/fleet-date.component';
import {Component,OnInit}from'@angular/core';import{CommonModule}from'@angular/common';import{RouterLink}from'@angular/router';import{HttpClient}from'@angular/common/http';
@Component({selector:'app-work-orders',standalone:true,imports:[FleetGridDirective,FleetDateComponent,CommonModule,RouterLink],template:`
<section class="page"><div class="title"><div><h2>Work Orders</h2><p>Track each service job, assigned supervisor and work progress.</p></div></div>
<div class="note"><b>One Work Order can contain both:</b> Scheduled PM work generated from the PM Task Matrix + Additional Work from Maintenance Requests / complaints.</div>
<div class="card"><div class="fleet-grid-scroll" role="region" aria-label="Records" tabindex="0"><table fleetGrid><tr><th>Work Order</th><th>Service Opened On</th><th>Completed On</th><th>Vehicle</th><th>Sources</th><th>Tasks</th><th>Open Defects</th><th>Priority</th><th>Bay</th><th>Assigned To (Supervisor)</th><th>Status</th><th>Total Cost</th><th>Action</th></tr>
<tr *ngFor="let x of rows"><td><b>{{x.workOrderNumber}}</b></td><td class="date-cell"><app-fleet-date [value]="x.openedAt"></app-fleet-date></td><td class="date-cell"><app-fleet-date [value]="x.completedAt"></app-fleet-date></td><td>{{x.vehicle}}</td><td><span class="source" *ngIf="x.hasPm">Scheduled PM</span><span class="source extra" *ngIf="x.requestRefs?.length">{{x.requestRefs.join(', ')}}</span><span class="source" *ngIf="!x.hasPm">{{x.eventType||'Maintenance'}}</span></td><td>{{x.taskCount}}</td><td>{{x.openDefects}}</td><td>{{x.priority}}</td><td>{{x.bay||'-'}}</td><td>{{x.assignedSupervisor||'Unassigned'}}</td><td>{{x.status}}</td><td><b>₹{{x.totalCost|number:'1.0-0'}}</b></td><td><a class="btn btn-primary" [routerLink]="['/service-workspace',x.id]">Open Workspace</a></td></tr>
<tr *ngIf="!rows.length"><td colspan="13" class="empty">No Work Orders.</td></tr></table></div></div></section>`,styles:[`.page{padding:26px}.title p{color:#64748b}.note{background:#eef6ff;border:1px solid #bfdbfe;border-radius:8px;padding:10px 12px;margin:12px 0}.card{margin-top:14px}.source{display:inline-block;background:#dbeafe;color:#1d4ed8;padding:4px 7px;border-radius:12px;margin:2px;font-size:11px}.source.extra{background:#fef3c7;color:#92400e}.empty{text-align:center;color:#64748b;padding:18px}`]})
export class WorkOrdersComponent implements OnInit{rows:any[]=[];constructor(private h:HttpClient){}ngOnInit(){this.load()}load(){this.h.get<any[]>('/api/work-orders').subscribe(x=>{this.rows=x;for(const r of this.rows){r.hasPm=r.eventType==='PM';r.requestRefs=[];this.h.get<any>(`/api/work-orders/${r.id}/costs`).subscribe(c=>r.totalCost=c.total);this.h.get<any[]>(`/api/tasks?jobCardId=${r.id}`).subscribe(ts=>{const refs=new Set<string>();for(const t of ts){const m=String(t.description||'').match(/^(MR-[^ ·]+)/);if(m)refs.add(m[1])}r.requestRefs=Array.from(refs)})}})}}
