import {Component,OnDestroy} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {Router,NavigationEnd} from '@angular/router';
import {Subscription} from 'rxjs';
@Component({selector:'app-page-tools',standalone:true,imports:[FormsModule],template:`<div class="page-tools"><label>Search this screen <input [(ngModel)]="query" (keyup.enter)="search()" placeholder="Search loaded table records"></label><button (click)="search()">Search</button><button (click)="clear()">Clear</button><button (click)="csv()">Export CSV</button><button (click)="print()">Print / PDF Report</button><small role="status">{{message||'Reports contain the currently loaded, filtered records.'}}</small></div>`,styles:[`.page-tools{display:flex;gap:10px;flex-wrap:wrap;align-items:end;padding:12px 24px;border-bottom:1px solid #dce4ef;background:#fff}.page-tools label{font-size:12px;display:grid;gap:4px}.page-tools input,.page-tools button{padding:8px 11px;border:1px solid #c7d4e3;border-radius:6px;background:white;color:#173b67}.page-tools small{color:#65758b;font-size:11px;align-self:center}@media print{:host{display:none}}`]})
export class PageToolsComponent implements OnDestroy {
 query='';message='';private hidden=new Set<HTMLTableRowElement>();private sub:Subscription;
 constructor(router:Router){this.sub=router.events.subscribe(e=>{if(e instanceof NavigationEnd)this.clear()})}ngOnDestroy(){this.clear();this.sub.unsubscribe()}
 root(){return document.getElementById('fleet-page-content')}
 tables(){return Array.from(this.root()?.querySelectorAll<HTMLTableElement>('table')||[]).filter(t=>t.getClientRects().length>0)}
 clear(){for(const row of this.hidden)row.hidden=false;this.hidden.clear();this.query='';this.message=''}
 search(){for(const row of this.hidden)row.hidden=false;this.hidden.clear();const q=this.query.trim().toLowerCase();let found=0;for(const table of this.tables()){for(const row of Array.from(table.rows)){if(row.querySelector('th')||!row.cells.length)continue;if(q&&!row.textContent?.toLowerCase().includes(q)){row.hidden=true;this.hidden.add(row)}else found++}}this.message=found+' matching loaded rows. Use page filters to retrieve other records.';}
 csv(){const lines:string[][]=[];for(const t of this.tables()){const rows=Array.from(t.rows).filter(r=>!r.hidden&&r.getClientRects().length>0);const headings=rows.find(r=>r.querySelector('th'));const actions=new Set(headings?Array.from(headings.cells).map((c,i)=>/^actions?$/i.test(c.textContent?.trim()||'')?i:-1):[]);for(const row of rows){lines.push(Array.from(row.cells).filter((_,i)=>!actions.has(i)).map(c=>(c.innerText||c.textContent||'').trim()))}lines.push([])}if(!lines.length){this.message='No loaded table records to export. Use Print / PDF Report for this view.';return}const quote=(s:string)=>'"'+(/^[\s]*[=+@-]/.test(s)?"'"+s:s).replace(/"/g,'""')+'"';const content='\uFEFF'+lines.map(r=>r.map(quote).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Montra-'+location.pathname.replace(/[^a-z0-9]+/gi,'-')+'-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);this.message='Exported the displayed table records.'}
 print(){window.print()}
}
