import {Component,Input,OnChanges,OnDestroy,HostListener,ViewChild,ElementRef} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule} from '@angular/forms';
import {HttpClient} from '@angular/common/http';
import {Subscription} from 'rxjs';
@Component({selector:'app-veerai',standalone:true,imports:[CommonModule,FormsModule],template:`
<button *ngIf="!open" class="launch" (click)="openPanel()" aria-label="Open Veerai">✦ Ask Veerai</button>
<section *ngIf="open" class="chat" role="dialog" aria-label="Veerai chat" [style.left.px]="left" [style.top.px]="top" [class.moved]="left!==null" [class.expanded]="expanded">
<header (pointerdown)="startDrag($event)"><div><b>✦ Veerai</b><small>Montra service assistant</small></div><div class="controls"><button (click)="newChat()" aria-label="New chat and vehicle" title="New chat and vehicle">↺</button><button (click)="expanded=!expanded" [attr.aria-label]="expanded?'Restore Veerai':'Expand Veerai'" [title]="expanded?'Restore':'Expand'">⛶</button><button (click)="open=false" aria-label="Minimise Veerai">−</button><button (click)="close()" aria-label="Close Veerai">×</button></div></header>
<div class="modebar"><button type="button" [class.selected]="mode==='chat'" (click)="mode='chat'">Chat</button><button type="button" [class.selected]="mode==='voice'" (click)="mode='voice'">Voice</button><select aria-label="Voice language" [(ngModel)]="language"><option value="en-IN">English</option><option value="hi-IN">हिन्दी</option><option value="ta-IN">தமிழ்</option><option value="ml-IN">മലയാളം</option></select></div>
<div class="context" *ngIf="contextLabel||jobId">{{contextLabel||'Using this service workspace'}} <button *ngIf="contextId&&!jobId" (click)="reset()">Clear</button></div>
<div class="messages" #messages role="log" aria-live="polite">
<div class="welcome" *ngIf="!turns.length"><h3>How can I help?</h3><p>Ask about a Montra fault, repair or service job. Include a vehicle number when needed.</p><button (click)="draft='What should I check if my Montra is not charging?'">Montra not charging?</button><button *ngIf="jobId" (click)="draft='What could explain this complaint, and what should we check next?'">Investigate this complaint</button></div>
<article *ngFor="let t of turns" [class.mine]="t.role==='user'"><small>{{t.role==='user'?'You':'Veerai'}}</small><p>{{t.text}}</p><details *ngIf="t.sources?.length"><summary>Evidence used</summary><div *ngFor="let s of t.sources"><a [href]="s.url" target="_blank" rel="noopener">{{s.id}} · {{s.label}}</a><pre>{{s.detail}}</pre></div></details></article>
<div class="choices" *ngIf="choices.length"><button *ngFor="let c of choices" (click)="choose(c)" [disabled]="busy">{{c.label}}</button></div>
<p *ngIf="busy" class="thinking" role="status">Veerai is thinking…</p>
<p *ngIf="error" class="error" role="alert">{{error}} <button (click)="retry()" *ngIf="lastQuestion&&!busy">Retry</button></p>
</div>
<form *ngIf="needsUnlock" (ngSubmit)="unlock()" class="unlock"><label>Unlock this browser for 8 hours<input type="password" name="access" [(ngModel)]="access" placeholder="Administrator-provided Veerai key" autocomplete="off"></label><button type="submit" [disabled]="busy||!access.trim()">Unlock</button></form>
<form (ngSubmit)="send()"><label class="sr-only" for="veer-message">Message Veerai</label><textarea id="veer-message" name="message" [(ngModel)]="draft" placeholder="Ask Veerai…" rows="2" maxlength="1500" (keydown.enter)="enter($event)"></textarea><button class="mic" [class.listening]="listening" type="button" (click)="toggleListening()" [disabled]="busy" [attr.aria-label]="listening?'Stop listening':'Speak to Veerai'" [title]="listening?'Stop listening':'Start microphone'">{{listening?'STOP':'MIC'}}</button><button *ngIf="speaking||busy" class="mic stop-speaking" type="button" (click)="stopAll()" aria-label="Stop Veerai" title="Stop Veerai">STOP</button><button class="send" type="submit" [disabled]="busy||!draft.trim()" aria-label="Send message">Send ↑</button></form>
<footer>AI guidance · Verify before acting. Job notes and chat are sent to AI.</footer>
</section>`,styles:[`
:host{font-family:Arial,sans-serif;color:#17304e}.launch{position:fixed;right:22px;bottom:22px;z-index:1100;background:#125ece;color:white;border:0;border-radius:28px;padding:14px 20px;box-shadow:0 6px 24px #16345a40;cursor:pointer}
.chat{position:fixed;right:22px;bottom:82px;width:420px;height:560px;max-width:calc(100vw - 24px);max-height:calc(100dvh - 100px);z-index:1200;background:white;border:1px solid #d4deeb;border-radius:18px;box-shadow:0 12px 48px #16345a40;display:flex;flex-direction:column;overflow:hidden}.chat.moved{right:auto;bottom:auto}.modebar{display:flex;gap:6px;align-items:center;padding:8px 12px;background:#f4f7fb;border-bottom:1px solid #e2e8f1}.modebar button{border:1px solid #c7d5e6;background:white;border-radius:7px;padding:6px 10px;color:#17304e}.modebar button.selected{background:#125ece;color:white}.modebar select{margin-left:auto;border:1px solid #c7d5e6;border-radius:7px;padding:6px;max-width:130px}.mic{border:1px solid #c7d5e6;background:white;border-radius:9px;padding:10px}
header{min-height:64px;box-sizing:border-box;display:flex;justify-content:space-between;align-items:center;gap:8px;padding:12px 16px;background:#123b73;color:white;cursor:move;touch-action:none}header b{font-size:19px}header small{display:block;font-size:11px;margin-top:3px;color:#d5e5ff}.controls{display:flex;gap:4px}.controls button{background:transparent;border:0;color:white;font-size:20px;padding:6px;min-width:30px}.context{font-size:12px;background:#eef4fc;padding:8px 12px;display:flex;justify-content:space-between}.messages{flex:1;overflow:auto;padding:16px;min-height:0;scroll-behavior:smooth}.welcome h3{margin:8px 0}.welcome p{font-size:14px;line-height:1.5;color:#576c85}.welcome button,.choices button{display:block;text-align:left;margin:8px 0;border:1px solid #d2dfef;border-radius:10px;background:white;padding:10px;font-size:13px;width:100%}article{background:#f0f4f9;border-radius:12px;padding:10px 12px;margin-bottom:12px;max-width:92%;font-size:14px;line-height:1.5}article.mine{background:#e5efff;margin-left:auto}article small{font-size:11px;font-weight:bold;color:#516d8b}article p{white-space:pre-wrap;overflow-wrap:anywhere;margin:4px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px}summary,a{color:#135eb9;font-size:12px;cursor:pointer}form{display:flex;align-items:end;gap:8px;border-top:1px solid #e2e8f1;padding:12px;background:white}textarea{flex:1;min-width:0;resize:none;border:1px solid #cad7e7;border-radius:10px;padding:10px;font:14px/1.4 Arial;box-sizing:border-box}.send{background:#125ece;color:white;border:0;border-radius:9px;padding:12px}button{cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}footer{font-size:10px;color:#64758b;padding:0 12px 10px}.error{color:#963c19;background:#fff3ec;padding:10px;font-size:13px}.thinking{font-size:13px;color:#516d8b}.unlock{background:#fff8e9;font-size:12px}.unlock input{display:block;width:100%;box-sizing:border-box;padding:8px;margin-top:6px;border:1px solid #d2dfef;border-radius:6px}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:500px){.chat,.chat.moved{left:12px!important;top:auto!important;right:12px!important;bottom:74px!important;width:auto;max-width:none;height:540px}.launch{right:12px;bottom:16px}}
.mic{border:2px solid #125ece!important;background:#eaf2ff!important;color:#125ece!important;border-radius:9px;padding:10px 8px;min-width:48px;height:44px;font-size:12px;font-weight:700}.mic.listening{background:#16803c!important;border-color:#0d5c2b!important;color:white!important}.stop-speaking{background:#b42318!important;border-color:#7a1712!important;color:white!important}.chat.expanded{width:min(900px,calc(100vw - 24px));height:min(820px,calc(100dvh - 100px))}.chat,textarea,article,button,select{font-family:"Nirmala UI","Noto Sans Tamil","Noto Sans Malayalam","Noto Sans Devanagari",Arial,sans-serif}`]})
export class VeeraiComponent implements OnChanges,OnDestroy{
 @Input() jobId='';@ViewChild('messages') messages?:ElementRef<HTMLDivElement>;
 needsUnlock=false;access='';open=false;expanded=false;draft='';busy=false;error='';contextId:string|null=null;contextLabel='';turns:any[]=[];choices:any[]=[];lastQuestion='';left:number|null=null;top:number|null=null;mode:'chat'|'voice'='chat';language='en-IN';listening=false;speaking=false;
 private request?:Subscription;private drag:any;private recorder?:MediaRecorder;private audioChunks:Blob[]=[];
 constructor(private http:HttpClient){}
 ngOnChanges(){this.reset();}ngOnDestroy(){this.request?.unsubscribe();this.stopListening();this.stopSpeaking();}
 openPanel(){this.open=true;this.scroll();}close(){this.cancel();this.open=false;this.access='';}
 reset(){this.cancel();this.turns=[];this.choices=[];this.error='';this.access='';this.contextId=this.jobId||null;this.contextLabel='';this.lastQuestion='';this.draft='';}
 newChat(){this.cancel();this.stopListening();this.stopSpeaking();this.turns=[];this.choices=[];this.error='';this.access='';this.contextId=null;this.contextLabel='';this.lastQuestion='';this.draft='';}
 cancel(){this.request?.unsubscribe();this.busy=false;}
 async toggleListening(){if(this.listening){this.stopListening();return}if(!navigator.mediaDevices?.getUserMedia||!(window as any).MediaRecorder){this.error='This browser does not support microphone recording. Please use Microsoft Edge or Google Chrome.';return}try{this.error='';const stream=await navigator.mediaDevices.getUserMedia({audio:true});this.audioChunks=[];this.recorder=new MediaRecorder(stream,{mimeType:'audio/webm'});this.recorder.ondataavailable=(e:BlobEvent)=>{if(e.data.size)this.audioChunks.push(e.data)};this.recorder.onstart=()=>this.listening=true;this.recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());this.listening=false;const audio=new Blob(this.audioChunks,{type:'audio/webm'});if(audio.size)this.transcribe(audio)};this.recorder.start();}catch{this.error='Microphone permission was denied or unavailable.';this.listening=false;}}
 stopListening(){try{this.recorder?.stop()}catch{}this.listening=false;}
 transcribe(audio:Blob){const form=new FormData();form.append('audio',audio,'veerai.webm');this.busy=true;this.http.post<any>('/api/veerai/transcribe',form).subscribe({next:r=>{this.busy=false;this.draft=(r.text||'').trim();if(this.draft)this.error='Please check the mixed-language transcript, correct any words or numbers, then press Send.';},error:e=>{this.busy=false;this.error=e.error?.message||'Voice transcription failed. Please try again.';}});}
 speak(text:string){if(this.mode!=='voice'||!(window as any).speechSynthesis)return;const utterance=new SpeechSynthesisUtterance(text);utterance.lang=this.language;utterance.onstart=()=>this.speaking=true;utterance.onend=()=>this.speaking=false;utterance.onerror=()=>this.speaking=false;(window as any).speechSynthesis.cancel();(window as any).speechSynthesis.speak(utterance);}
 stopSpeaking(){if((window as any).speechSynthesis)(window as any).speechSynthesis.cancel();this.speaking=false;}
 stopAll(){this.cancel();this.stopSpeaking();this.stopListening();}
 @HostListener('document:keydown.escape') escape(){this.open=false;}
 enter(e:Event){const k=e as KeyboardEvent;if(!k.shiftKey&&!k.isComposing){k.preventDefault();this.send();}}
 send(){const text=this.draft.trim();if(!text||this.busy)return;this.draft='';this.submit(text,true);}
 retry(){if(this.lastQuestion&&!this.busy)this.submit(this.lastQuestion,false);}
 choose(c:any){this.contextId=c.id;this.contextLabel=c.label;this.choices=[];this.submit(this.lastQuestion,false,c.id);}
 submit(text:string,add:boolean,choice?:string){const history=this.turns.slice(-10).map(t=>({role:t.role,text:t.text}));if(add)this.turns.push({role:'user',text});this.lastQuestion=text;this.busy=true;this.error='';this.choices=[];this.scroll();
 this.request=this.http.post<any>('/api/veerai/chat',{message:text,jobId:this.contextId||this.jobId||null,selectedJobId:choice||null,history,language:this.language}).subscribe({next:r=>{this.busy=false;this.contextId=r.jobId||null;this.contextLabel=r.context||'';this.turns.push({role:'assistant',text:r.reply,sources:r.sources});this.choices=r.choices||[];this.speak(r.reply);this.scroll();},error:e=>{this.busy=false;this.needsUnlock=e.status===401;this.error=e.status===429?'Veerai is busy. Please wait a minute and retry.':e.error?.message||'Unable to reach Veerai. Please retry.';this.scroll();}});
 }
 unlock(){if(this.busy||!this.access.trim())return;this.busy=true;this.error='';this.request=this.http.post('/api/veerai/chat/session',{accessKey:this.access}).subscribe({next:()=>{this.access='';this.needsUnlock=false;this.busy=false;this.lastQuestion='';this.error='VeerAI unlocked. Enter your question and press Send once.';},error:e=>{this.access='';this.busy=false;this.error=e.status===429?'Too many attempts. Wait one minute, then try once.':e.error?.message||'Unable to unlock Veerai.';}});}
 scroll(){setTimeout(()=>{const el=this.messages?.nativeElement;if(el)el.scrollTop=el.scrollHeight;},0);}
 startDrag(e:PointerEvent){if((e.target as HTMLElement).closest('button'))return;const box=(e.currentTarget as HTMLElement).parentElement!.getBoundingClientRect();this.drag={x:e.clientX,y:e.clientY,left:box.left,top:box.top,width:box.width,height:box.height};e.preventDefault();}
 @HostListener('document:pointermove',['$event']) move(e:PointerEvent){if(!this.drag)return;this.left=Math.max(0,Math.min(window.innerWidth-this.drag.width,this.drag.left+e.clientX-this.drag.x));this.top=Math.max(0,Math.min(window.innerHeight-this.drag.height,this.drag.top+e.clientY-this.drag.y));}
 @HostListener('document:pointerup') endDrag(){this.drag=null;}
 @HostListener('window:resize') resize(){this.left=null;this.top=null;this.drag=null;}
}
